certbot/josepy

README.rst, setup.py
Just fixing up some URLs from `/jezdez/` to `/certbot/`.
=> Update URLs to the certbot organization

.travis.yml, pytest.ini, setup.py, src/josepy/__init__.py, src/josepy/test_util.py, tox.ini
This reverts commit 0232e4a0e8a25fd981ee4e52cf4b613fdefb6896 from #19.
=> Remove Python 2.6 and 3.3 support

setup.py
* Adds mypy and typing to dev3_extras option
Resolves #28
=> Add dev3 extras to setup.py

src/josepy/__init__.py
Part of https://github.com/certbot/josepy/issues/53.
=> Deprecate python 3.4 support

.travis.yml, setup.py, src/josepy/__init__.py, tox.ini
Fixes https://github.com/certbot/josepy/issues/53.
=> Drop python 3.4 support

.travis.yml
This is the equivalent of https://github.com/certbot/certbot/pull/7733 but for this repo.
=> Disable notifications from non-master branches

.travis.yml, setup.py, tox.ini
This is equivalent to what we did for Python 3.8 at https://github.com/certbot/josepy/pull/52.
=> Officially add Python 3.9 support

tools/release.sh
There's no rush on reviewing this, but I'm assigning Erica because she's the only other one who might use this script right now.
=> Help us remember to update the changelog

.editorconfig
=> Added an .editorconfig file.

CHANGELOG.rst, src/josepy/magic_typing.py, src/josepy/magic_typing_test.py
Fixes https://github.com/certbot/certbot/issues/8660.
=> Deprecate magic_typing

setup.py
This is the josepy version of https://github.com/certbot/certbot/pull/8639.
=> Combine dev and dev3 extras

.gitignore, .travis.yml, mypy.ini, setup.py, src/josepy/json_util.py, src/josepy/jwa.py, src/josepy/jwk.py, src/josepy/jwk_test.py, src/josepy/jws.py, src/josepy/magic_typing.py, src/josepy/util.py, tox.ini
My experience with static type checking and MyPy is a bit limited, but it's always a good way to educate yourself :)
There are still a bunch `:rtype:` annotations left, which I propose to replace with PEP484 syntax.
=> Added mypy to tests

CHANGELOG.rst
See https://github.com/certbot/josepy/issues/109.
=> Add JWKEC patch changelog entry

CHANGELOG.rst, tools/release.sh
Fixes https://github.com/certbot/certbot/issues/8783.
This is the equivalent of https://github.com/certbot/certbot/pull/9046 for this repo.
=> Change PGP keys

src/josepy/b64.py, src/josepy/json_util.py, src/josepy/jws.py, src/josepy/util.py
As a follow-up of https://github.com/certbot/certbot/pull/9073, this PR redefine some methods as generic ones and fix some types.
=> Add generic methods

CHANGELOG.rst, pytest.ini, src/josepy/__init__.py
=> Deprecate Python 3.6 support

poetry.lock, pyproject.toml
We use twine to upload our packages to PyPI and it's currently not being installed in the dev venv.
=> Add twine to dev deps

poetry.lock, src/josepy/json_util.py
=> repin dependencies

CONTRIBUTING.md, README.rst
i also made a couple changes to the README to make it shorter and hopefully more readable
=> add docs about updating dependencies

.github/dependabot.yml
this enables dependabot to automate the creation of PRs like https://github.com/certbot/josepy/pull/176. i've tested this on [my fork](https://github.com/bmw/josepy/pulls) and it seems to work pretty well imo
=> enable dependabot PRs

tools/release.sh
This does the same thing I did in https://github.com/certbot/certbot/pull/9985 for the same reasons.
=> Switch from gpg2 to gpg

.github/workflows/check.yaml, CHANGELOG.rst, pyproject.toml, tox.ini
this is based on https://github.com/certbot/josepy/pull/169
i also cleaned up some references to python 3.7 on the same lines that were missed in https://github.com/certbot/josepy/pull/186
=> add python 3.13 support

tools/release.sh
=> Remove u marker from python strings to make black happy

.github/workflows/assigned.yaml
Copied from https://github.com/certbot/certbot/pull/10191
=> [TOOLING] Add automation for when a PR or Issue is assigned

.github/workflows/assigned.yaml, .github/workflows/review_requested.yaml
This is a duplicate of https://github.com/certbot/certbot/pull/10345 for this repo
=> Allow notification of two reviewers being assigned to a PR and two issue assignees
