setup.py, src/josepy/test_util.py
From .travis.yml and tox, it looks like only Python 2.7 and 3.4-3.6 are supported.
That means we can remove some redundant code for those EOL versions.
=> Remove redundant Python 2.6 and 3.3 code

setup.py
Currently https://pypi.org/project/josepy/ says
Project Description
UNKNOWN
which is a bit unfriendly.  Let's fix that.
=> Use README.rst as long_description for PyPI

src/josepy/jwa.py, src/josepy/jwa_test.py
Prefer new  `sign()` and `verify()` methods introduced in `cryptography` v.1.4. The old `signer()` and `verifier()` are being deprecated. Fall back to the old methods if the new ones don't exist in order to keep supporting older distributions not shipping recent enough version.
Fixes: #13
=> Prefer new python-cryptography methods sign and verify

.gitignore, tools/release.sh
This is a quick port of Certbot's release script to this repo. I want to rethink our automation around releases in the long term, but this seemed like a better approach to me than either doing the release manually or taking the time to figure out the best long term automation right now.
The first commit here just copies the release script from the Certbot repo. The 2nd commit makes the necessary changes.
=> Add release script

CHANGELOG.rst
Unlike Certbot, the changelog here is actually included in the package so let's get it updated before the release.
=> Update changelog for 1.1.0

.gitignore, src/josepy/magic_typing.py, src/josepy/magic_typing_test.py
Updates gitignore to include venv/ and .pytest_cache (for pytest update change in default naming)
Add magic_typing and magic_typing_tests as copies from certbot/acme updated for use with josepy
=> Add magic_typing and magic_typing_tests, update .gitignore

setup.py
Versions of setuptools [prior to 18.4][18.4] would not invoke tests unless a value for `test_suite` was provided. To simplify packaging on distros that have old versions of setuptools (e.g. CentOS 7, Debian 8, Ubuntu 14.04), we specify a value for it.
[18.4]: https://setuptools.readthedocs.io/en/latest/history.html#id314
=> Add test_suite to setup.py

src/josepy/interfaces.py, src/josepy/jwa.py, src/josepy/util.py
Starting with Python 3.8, abstract types from `collections` will need to be imported from the `collections.abc`. Currently on recent versions of Python, theses types can be imported both from `collections` and `collections.abc`, but will generated a warning about support drop for Python 3.8 if `collections` is used.
This PR allows to use `collections.abc`, and falls back to `collections` if necessary.
=> Make code compatible with Python >= 3.8 towards collections module

pytest.ini, setup.py
As you can see at https://github.com/certbot/josepy/runs/75221064, we're having some problems with `isort`.
It seems the new version is no longer properly recognizing that `josepy` is a first party library and it's not happy with our `__init__.py` file. Let's just remove these checks for now so tests pass again.
=> Temporarily remove isort

.travis.yml
Now that Travis has real [Xenial support](https://docs.travis-ci.com/user/reference/xenial/), I figure we might as well use it for all environments to get later and greater versions of software and simplify the Travis config.
=> Always use xenial

.travis.yml
Now that Travis has real [Xenial support](https://docs.travis-ci.com/user/reference/xenial/) we don't need to use `sudo: true` which should speed up the build slightly.
=> Don't require sudo

README.rst
As part of migrating away from the now deprecated support for GitHub services, our Travis config has moved from travis-ci.org to travis-ci.com. This PR updates the links to our build status to use travis-ci.com.
=> Change build status links to travis-ci.com

.travis.yml
I tested this at https://travis-ci.com/certbot/josepy/builds/113496549 which successfully sent a notification to the new channel. @joohoi, I believe you were in the channel to see this message, but if not, we can trigger the build again.
Because I had to look up how to do this again, I added a comment describing how this value was created.
=> Add IRC channel notifications.

.travis.yml, setup.py, tox.ini
Certbot supports Python 3.8 so josepy needs to as well.
=> Add support for Python 3.8.

src/josepy/util.py
Softens the language a bit and acknowledges that the original implementation is indeed from Python. Fixes #54
=> Clarify origin of abstractclassmethod implementation

.travis.yml
We were previously using `python: 3.8-dev` to allow us to test against Python 3.8 before it was released. Now that Python 3.8 is out and the development branch is [causing errors for us](https://travis-ci.com/certbot/josepy/jobs/286198517), let's just use the stable version of Python 3.8.
=> Don't use the development branch of Python 3.8

tools/release.sh
Fixes https://github.com/certbot/josepy/issues/61 and applies the same fix to `virtualenv` commands as https://github.com/certbot/certbot/pull/7832.
@ohemorange, are you able to review this small PR when you get a minute?
=> Update release.sh to Python 3 and fix virtualenv

constraints.txt, tox.ini
Fixes #63.
Took some finagling to get a working set of dependencies. Some I copied from Certbot, some are based on going back through releases to find a compatible set.
=> Pin flake8/all Python dependencies in tests

examples/pem_conversion.py
added an example script, as suggested in #65, illustrating how to convert certbot keys to/from PEM
=> added examples/pem_coversion.py

src/josepy/__init__.py
Now that Certbot no longer supports Python 3.5 which is EOL'd next month, let's deprecate it here. Once this lands, I'll try to squeeze in a release this package and then we can drop Python 3.5 support in master.
This was based on #56.
=> Deprecate Python 3.5 support

.travis.yml, setup.py, src/josepy/__init__.py, tox.ini
Now that [josepy 1.4.0](https://pypi.org/project/josepy/1.4.0/) is out deprecating Python 3.5 support, let's drop support for it in `master`. This PR is based on #58.
=> Drop Python 3.5 support

setup.py
Fixes https://github.com/certbot/certbot/issues/8405.
=> Stop using deprecated setuptools functionality

.travis.yml
We originally used `3.9-dev` here so we could test Python 3.9 support before it was released and offered by Travis. Now Travis offers the stable version of Python 3.9 though so I don't think we need to or should be testing using the development branch of Python 3.9 anymore.
More about the Python versions offered by Travis can be found at https://docs.travis-ci.com/user/languages/python/#specifying-python-versions.
=> Stop using the development branch of Python 3.9

src/josepy/__init__.py
This was based on https://github.com/certbot/josepy/pull/67.
Once this PR is merged and included in a release, we can drop Python 2.7 support here as well.
=> Deprecate support for Python 2.7

src/josepy/interfaces.py, src/josepy/jwa.py, src/josepy/util.py
Should be good as of Python 3.3+ :) Will also increase code coverage slightly by removing some dead catch-blocks ;)
=> collections.abc is supported on all supported Python versions.

pytest.ini
In the Certbot repo we configure `pytest` to error on warnings. See https://github.com/certbot/certbot/blob/d3ca6af9824d4715f4312724e32a26c270696db8/pytest.ini#L12-L13.
I think this is a good practice, I noticed we're not doing this here, and I think we should. Warnings are usually used to warn about things like uses of deprecated code and erroring on them ensures we see them and handle them appropriately.
=> Error on warnings

src/josepy/interfaces_test.py, src/josepy/json_util_test.py, src/josepy/jwa_test.py, src/josepy/jwk_test.py, src/josepy/jws_test.py, src/josepy/magic_typing_test.py, src/josepy/util_test.py
They provide better output and debugging. I split also a couple of instances of `assertTrue(all` to call `assertIs` for each of the statements.
=> Updated unittest assert to Python 3 support.

src/josepy/magic_typing_test.py
This test doesn't work with newer versions of `cryptography`. See https://github.com/certbot/josepy/pull/88#issuecomment-786911443.
Since `magic_typing` is deprecated and `typing` should always be available since we only support Python 3.6+, I think we should just delete this test.
=> Remove broken test for typing import failure

src/josepy/jwa.py, src/josepy/jwa_test.py, src/josepy/jwk.py
The r||s encoding is wrong for ec keys and signatures with leading zeros.
This results in bad signatures, I've come across:
"Parse error reading JWS: EC public key has incorrect padding"
"failed to unmarshal JWK: square/go-jose: invalid EC public key, wrong length"
Leading zero happens very frequently for ES512, rare with ES256.
This was already wrong in my proposal for r||s and just got ported to using cryptography api.
int.to_bytes requires python >= 3.2
bytes.fromhex python >= 3.0
so they are safe to use here.
=> EC signature padding

src/josepy/interfaces.py, src/josepy/json_util.py, src/josepy/jwk.py, src/josepy/jws.py, src/josepy/util.py
This include dict comprehension, `{**a, **b}` dict merging, and using only literals (`{}` instead of `dict`)
=> Updated Python dict-constructs to Python 3.6+.

src/josepy/jwa.py, src/josepy/jwa_test.py, src/josepy/jwk.py, src/josepy/jwk_test.py
Hi,
this patch changes the encoding of ec coordinate parameters to be static in length according to rfc.
Without this patch there is a chance to run into
```
Deserialization error: Expected parameter "{x,y}" to be range(a, b) bytes after base64-decoding; got c bytes instead
```
=> JWKEC - key en/de-coding

constraints.txt, setup.py, tox.ini
These constraints hadn't been updated since we added mypy to our dev or tests extras so mypy wasn't pinned and a new release came out yesterday causing our tests to fail. This PR adds mypy to constraints and pins it to the previously working version for now.
Additionally, the constraints file wasn't being used in the tox config for mypy. To fix this, I moved mypy to the test extras and deleted the mypy deps setting in the tox config so it is inherited from the default testenv which uses the constraints file.
I also added quotes around .[dev,tests] because without it zsh complains:
```
$ python3 -m pip install -e .[dev,tests] && pip freeze
zsh: no matches found: .[dev,tests]
```
=> Update constraints and pin mypy

CHANGELOG.rst, setup.py
Fixes https://github.com/certbot/josepy/issues/102.
As seen at https://docs.pytest.org/en/stable/changelog.html#id1406, `pytest` added `pytest-cache` functionality in the version 2.8 which is what we specify as our minimum pytest version.
=> Remove pytest-cache dep

src/josepy/jws_test.py
Quite a bit faster, and more Pythonic. I used https://pypi.org/project/flake8-comprehensions/ and this was the only one; it probably should have been included when I did #96 
```
❯ ipython3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: %timeit set(['alg'])
125 ns ± 0.85 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [2]: %timeit {'alg'}
42.4 ns ± 0.308 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
=> Use set literal in JWSTest.test_compact_lost_unprotected

.github/workflows/check.yaml, .gitignore, mypy.ini, src/josepy/b64.py, src/josepy/errors.py, src/josepy/interfaces.py, src/josepy/json_util.py, src/josepy/jwa.py, src/josepy/jwk.py, src/josepy/jws.py, src/josepy/jws_test.py, src/josepy/magic_typing.py, src/josepy/test_util.py, src/josepy/util.py
As part of a global effort to bring more types in the Certbot project, this PR adds type annotations to all methods/functions in `josepy` out of tests modules.
=> Add types to functions (out of tests modules) in josepy

MANIFEST.in
This PR adds the required update to `josepy` to be compliant with [PEP-561](https://www.python.org/dev/peps/pep-0561/).
Once merged and a new version is released, third parties that rely on `josepy` will get their type utilities inspecting the code of `josepy` so that inline type annotations are taken into account in type checks.
Basically, no more `Skipping analyzing josepy: found module but no type hints or library stubs`.
=> Make `josepy` PEP-561 compliant to auto-discover inline types annotations

CHANGELOG.rst, src/josepy/__init__.py, src/josepy/json_util.py, src/josepy/json_util_test.py, src/josepy/jws.py
This PR provides a new function, `josepy.field`, that allows to declare fields with appropriate type annotations to express the type of the actual value of the field. An exemple is provided in the associated docstring, and actual usage of it is done in the `jws` module.
=> Allow to add type annotations to fields defined in a `JSONObjectWithFields`

.github/workflows/check.yaml
Prior to https://github.com/certbot/josepy/pull/104, CI was configured to run tests on pushes to all branches. I personally find this setup useful as I've since resorted to things like [opening a draft PR if I want to test things in CI](https://github.com/certbot/josepy/pull/123).
=> Test all branches

src/josepy/__init__.py
I'm not sure if those were left out intentionally.
=> Add missing imports to __init__

src/josepy/interfaces.py
Fix two type hinting issues that I stumbled upon:
* Use generics for `from_json()` and `json_loads()`. This way the return value in a subclass is (correctly) typehinted to that subclass. See also: https://mypy.readthedocs.io/en/stable/generics.html#generic-methods-and-generic-self
* `json.loads()` also accepts bytes, so `json_loads()` actually does too.
=> Fix from_json and json_loads typehints

.github/workflows/check.yaml, setup.cfg, setup.py, src/josepy/__init__.py, src/josepy/interfaces.py, src/josepy/json_util.py, src/josepy/jwa.py, src/josepy/jwk.py, src/josepy/jws.py, src/josepy/magic_typing.py, src/josepy/util.py, tests/b64_test.py, tests/json_util_test.py, tests/jwa_test.py, tests/jwk_test.py, tests/jws_test.py, tests/magic_typing_test.py, tests/test_util.py, tests/util_test.py, tox.ini
I think it'd make sense to activate `flake8` as well as introducing a standardized way of importing things.
There are still various comments relating to how pylint should work, but it doesn't seem to be used. Maybe those could be deleted/evaluated at some point. 
`E501` (maximum line length) should also be fixed. There aren't many places where it's wrong.
=> Introduce linting (flake8 and isort)

src/josepy/interfaces.py, src/josepy/json_util.py, src/josepy/jwa.py, src/josepy/jwk.py, src/josepy/jws.py, src/josepy/util.py, tests/interfaces_test.py, tests/json_util_test.py, tests/jwa_test.py, tests/jwk_test.py, tests/util_test.py
Considering pylint is not really used in the project, perhaps these markers/annotations can be removed.
=> Remove # pylint markers.

tools/release.sh
This PR does two things:
1. It fixes only a subset of our tests running in the release script. More info at https://github.com/certbot/josepy/pull/129#discussion_r806239144.
2. The new major version of `pytest` raises deprecation warnings about `pytest-flake8` which we've configured `pytest` to error on. See https://docs.pytest.org/en/7.0.x/changelog.html#deprecations. This is fixed in https://github.com/certbot/josepy/pull/129, but let's use our constraints file to avoid this problem for now. We use our pinned dependencies in the Certbot release script too since https://github.com/certbot/certbot/pull/6602.
=> Fix release script

tools/release.sh
`python` works for me locally because I use `pyenv` and have `python` set to a version of `python3` when I'm working on Certbot stuff. `python` doesn't work without `pyenv` on macOS or Debian based distros. To fix this, `python3` can be used instead.
I did this on the Certbot release script in https://github.com/certbot/certbot/pull/7918.
=> Use python3 in the release script

.github/workflows/check.yaml, README.rst
[We no longer use it on the main Certbot repo](https://github.com/certbot/certbot/pull/7811) and it's been repeatedly failing for us here recently.
=> Stop using codecov

src/josepy/util.py
A tiny little edit in the doc string for `ComparableECKey`.
=> s/RSA/EC/ for ComparableECKey

.readthedocs.yaml, tools/release.sh
Our readthedocs build started failing due to a change in pip. See https://readthedocs.org/projects/josepy/builds/18224913/.
Luckily, Poetry added the ability to export constraint.txt files over the weekend. See https://github.com/python-poetry/poetry-plugin-export/blob/dd3b674d21079af615979eda241385f550e3f4ae/CHANGELOG.md#110---2022-10-01.
I updated things to make use of this and you can see the readthedocs build passing with this change at https://readthedocs.org/projects/josepy/builds/18238149/. I also edited the release script to fail fast if poetry export doesn't have constraints.txt support.
Finally, I switched the poetry export flags `--dev` for `--with dev` as `--dev` is deprecated as described at https://github.com/python-poetry/poetry-plugin-export/tree/dd3b674d21079af615979eda241 …
=> Use proper constraints

.github/workflows/check.yaml
Some of these were using old/deprecated features and node versions, leading to a bunch of build warnings.
=> Update our github action versions

CONTRIBUTING.md, README.rst, tox.ini
I didn't like how `CONTRIBUTING.md` wasn't referenced in the README or how [`tox` didn't run tests that our CI fails on](https://github.com/certbot/josepy/blob/3e936853a12123b2a9d5b16fa99874d872826a9d/.github/workflows/check.yaml#L39-L48).
=> Improve tox and docs

poetry.lock, pyproject.toml
https://github.com/certbot/josepy/pull/155 broke our [docs build](https://readthedocs.org/projects/josepy/builds/19657395/) because for some reason Poetry's solution to dependency resolution in that PR downgraded Sphinx to a version that doesn't work on Python 3.10. You can see this downgrade in that PR by looking for the lines under `name = "sphinx"` in `poetry.lock`.
This PR fixes the problem by specifying a requirement on a new version of Sphinx on Python>=3.10.
=> Fix docs by updating Sphinx

poetry.lock, pyproject.toml
https://github.com/certbot/josepy/pull/157 fixed the problem locally, but [failed on readthedocs](https://readthedocs.org/projects/josepy/builds/19705150/). I believe that failure is due to https://github.com/python-poetry/poetry-plugin-export/issues/168.
To fix this, I just unconditionally tightened our Sphinx dependency. While I initially tried not to do this, I don't think it's worth the effort and I really doubt it will be a problem for people. If it is, we can always consider doing something fancier in a followup release. I also changed the minimum version to `4.3.0` based on [Sphinx's changelog](https://github.com/sphinx-doc/sphinx/blob/d50ae3c1c917cfa075125ab44c0c8f0eb7aad3ed/CHANGES#L775-L781).
Unfortunately, that change wasn't enough though because `poetry` then selected an …
=> Actually fix our docs build

poetry.lock, pyproject.toml, tests/test_util.py
When working on #157, I got errors because [the new version of `setuptools` deprecates `pkg_resources`](https://setuptools.pypa.io/en/latest/history.html#v67-5-0). To fix that, I used the "Attention" message at the top of https://setuptools.pypa.io/en/latest/pkg_resources.html and https://importlib-resources.readthedocs.io/en/latest/index.html. Importing `testdata` as a package like this after adding `__init__.py` Just Works™ for the same reason `import test_util` works.
=> Stop using pkg_resources

.git-blame-ignore-revs, .github/workflows/check.yaml, .pre-commit-config.yaml, README.rst, poetry.lock, pyproject.toml, setup.cfg, src/josepy/b64.py, src/josepy/errors.py, src/josepy/interfaces.py, src/josepy/json_util.py, src/josepy/jwa.py, src/josepy/jwk.py, src/josepy/jws.py, src/josepy/magic_typing.py, src/josepy/util.py, tests/b64_test.py, tests/errors_test.py, tests/interfaces_test.py, tests/json_util_test.py, tests/jwa_test.py, tests/jwk_test.py, tests/jws_test.py, tests/magic_typing_test.py, tests/test_util.py, tests/util_test.py, tox.ini
This PR sets up [black](https://github.com/psf/black), the "uncompromising code formatter", which is maintained on GitHub under the Python Software Foundation, has become very popular, and [is used by many projects](https://github.com/psf/black#used-by) including pyca's cryptography which I feel I often point to as an example of a well maintained project. Using a code formatter like this gives our code a consistent style and automatically fixes many problems our linter would otherwise yell about and make us fix manually.
The first commit here was entirely programmatically generated. To create it, first I installed black with `pip` into the virtual environment and then I ran the command put in the commit message.
The second commit was made manually. I added the first commit to …
=> Is this the part where I say "paint it black"?

setup.cfg, tox.ini
We don't need this file and can configure flake8 in tox.ini. See https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations.
=> Remove setup.cfg

CHANGELOG.rst, pyproject.toml, src/josepy/__init__.py, tests/init_test.py
Based on https://github.com/certbot/josepy/pull/132.
Tests may be overkill, but adding some quick tests didn't seem like a bad idea to me.
=> Deprecate Python 3.7

.readthedocs.yaml, docs/requirements.txt
i want this to try to help get automated dependabot PRs working to ideally automate some of that work for us. currently, the inclusion of this `requirements.txt` file that references a `constraints.txt` file that is generated on the fly as needed on top of our conventional poetry setup confuses the hell out of dependabot. i've been able to get things working after the changes here on my fork
this PR [seems to work on readthedocs](https://readthedocs.org/projects/josepy/builds/24593984/)
=> simplify & standardize poetry usage with readthedocs

pyproject.toml
Without this, pyca/cryptography's downstream tests currently fail.
The actual warning is being addressed in #182
=> Ignore warning that CSRs are deprecated in pyOpenSSL

CHANGELOG.rst, pyproject.toml, src/josepy/__init__.py, tests/init_test.py
this is based on https://github.com/certbot/josepy/pull/165
=> deprecate python 3.8 support

docs/conf.py
Sphinx v8 no longer supports intersphinx_mapping being a direct map; it now must be a map with identifiers and tuples.  This fixes a FTBFS downstream in Debian, bug #1090148.
=> Switch intersphinx_mapping to new format

tests/util_test.py
Since we're likely to deprecate this whole function soon anyway, I am putting the warning filter directly in the code. This fixes the tests currently [failing](https://github.com/certbot/josepy/actions/runs/12604702846) on master.
=> Filter warning caused by deprecated pyopenssl usage of datetime

.github/workflows/check.yaml, CHANGELOG.rst
For the same reasons as in the Certbot change (https://github.com/certbot/certbot/commit/84c8dbc52a14f9dbbe6de53779eaed3058109b9e)
=> change master to main

.readthedocs.yaml
This is now required for our docs to build, as specified here: https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
=> Specify sphinx config file location in .readthedocs.yaml

.github/CODEOWNERS, .github/dependabot.yml
this is a response to https://github.com/certbot/josepy/pull/223#issuecomment-2892664678
we could limit codeowners to only match pinning changes to mimic how dependabot worked, but i personally think automatic assignment of any new PRs is pretty nice. maybe if this works well, we could even try it on the certbot repo?
i propose we try it here and see how we feel about it
=> switch to codeowners

CHANGELOG.rst, pyproject.toml, src/josepy/__init__.py, tests/init_tests.py
fixes https://github.com/certbot/josepy/issues/239. this PR was based on https://github.com/certbot/josepy/pull/194
=> deprecate python 3.9 support

.pre-commit-config.yaml, pyproject.toml
https://black.readthedocs.io/en/stable/change_log.html#id1
https://flake8.pycqa.org/en/latest/release-notes/7.1.2.html
https://flake8.pycqa.org/en/latest/release-notes/7.2.0.html
https://flake8.pycqa.org/en/latest/release-notes/7.3.0.html
https://github.com/PyCQA/isort/releases/tag/6.0.0
https://github.com/PyCQA/isort/releases/tag/6.0.1
=> Update pre-commit versions
